### ISSUE TITLE
Add some free API

### ISSUE THREAD

**Issue by sunilsj99** [sunilsj99/Free-API#1]
Add some free api and mentions their links in readme file.

**Comment by DynamiteC** [comment]
I will add some, but how do you want your readme to be looked like?

**Comment by sunilsj99** [comment]
@DynamiteC  You can add the link to the api documentation and also you can add some details like what is api all about like it is a weather api or some other api

**Comment by DynamiteC** [comment]
Okay, Boss.

**Comment by DynamiteC** [comment]
Use of Google and Other Open source site is viable right?

**Comment by managedkaos** [comment]
Hello!  I will add some APIs (at least one that I can think of right now) but want to know:  Can I please sort the list?  It will be easier to look read from top to bottom.

**Comment by sunilsj99** [comment]
@managedkaos definitely you can sort the list if you can !! it will be easier to read. GO ON !! 👍

**Comment by managedkaos** [comment]
OK submitted initial PR.  I will try to sort it.
